name: Deploy Laravel Application to Hostinger via FTP

on:
  push:
    branches:
      - main  # or whatever branch you want to trigger deployment

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Install Dependencies
      run: |
        composer install --no-dev --optimize-autoloader

    - name: Deploy to Hostinger via FTP
      uses: SamKirkland/FTP-Deploy-Action@4.3.2
      with:
        server: 154.49.247.205  # or 154.49.247.205
        username: ${{ secrets.FTP_USERNAME }}
        password: ${{ secrets.FTP_PASSWORD }}
        port: 21  # Default FTP port
        local-dir: ./  # Directory with your Laravel project
        server-dir: /  # The directory where you want to deploy your files
        log-level: verbose  # Detailed logging for debugging
        timeout: 600  # Increase timeout to prevent connection timeout issues
