name: Deploy Laravel Application to Hostinger via FTP

on:
  push:
    branches:
      - main  # Trigger deployment on push to main branch

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Install Dependencies
      run: |
        composer install --no-dev --optimize-autoloader

    - name: Deploy Laravel files (excluding public) to root directory
      uses: SamKirkland/FTP-Deploy-Action@4.3.2
      with:
        server: ${{ secrets.FTP_SERVER }}  # The FTP server address, make sure it's added in your GitHub Secrets
        username: ${{ secrets.FTP_USERNAME }}
        password: ${{ secrets.FTP_PASSWORD }}
        port: 21  # Default FTP port
        local-dir: ./  # Root directory of your Laravel project
        server-dir: ../  # Move one level up from public_html (root of your subdomain)
        exclude: |  # Files/folders to exclude from the deployment
          .git*
          node_modules/
          vendor/
          public/  # Exclude public folder contents
          storage/logs/
        log-level: verbose  # Detailed logging for debugging
        timeout: 600  # Increased timeout to prevent connection issues
