name: Deploy Laravel Application to Hostinger via FTP

on:
  push:
    branches:
      - main  # Trigger deployment on push to main branch

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Install Dependencies
      run: |
        composer install --no-dev --optimize-autoloader

    - name: Deploy Laravel files (excluding public) to root directory (outside public_html)
      uses: SamKirkland/FTP-Deploy-Action@4.3.2
      with:
        server: ${{ secrets.FTP_SERVER }}
        username: ${{ secrets.FTP_USERNAME }}
        password: ${{ secrets.FTP_PASSWORD }}
        port: 21  # Default FTP port
        local-dir: ./  # Root directory of your Laravel project
        server-dir: /  # Path to the root directory (outside public_html)
        exclude: |
          .git*
          node_modules/
          vendor/
          public/  # Exclude public folder contents
          storage/logs/
        log-level: verbose
        timeout: 600

    - name: Deploy public folder contents to public_html
      uses: SamKirkland/FTP-Deploy-Action@4.3.2
      with:
        server: ${{ secrets.FTP_SERVER }}
        username: ${{ secrets.FTP_USERNAME }}
        password: ${{ secrets.FTP_PASSWORD }}
        port: 21
        local-dir: ./public/  # Only deploy the public folder
        server-dir: /public_html/  # Path to the public_html folder on Hostinger
        exclude: |
          .git*
        log-level: verbose
        timeout: 600
