name: Deploy Laravel to Hostinger

on:
  push:
    branches:
      - main  # Trigger deployment when you push to the 'main' branch

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Install Dependencies
      run: |
        composer install --optimize-autoloader --no-dev
        npm install
        npm run prod

    - name: Deploy to Hostinger via FTP
      uses: SamKirkland/FTP-Deploy-Action@4.3.2
      with:
        server: ftp://your-hostinger-server.com
        username: ${{ secrets.FTP_USERNAME }}
        password: ${{ secrets.FTP_PASSWORD }}
        local-dir: ./ # Upload the entire repository
        server-dir: /public_html/ # Adjust to your folder structure
        exclude: |
          .git*
          node_modules/
          vendor/

    - name: Finalize Deployment
      run: |
        php artisan migrate --force
        php artisan config:cache
        php artisan route:cache
        php artisan view:cache
