name: Deploy Laravel Application to Hostinger via FTP

on:
  push:
    branches:
      - main  # Trigger deployment on push to main branch

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Install Dependencies
      run: |
        composer install --no-dev --optimize-autoloader

    - name: Deploy Laravel files (excluding public) to root directory
      uses: SamKirkland/FTP-Deploy-Action@4.3.2
      with:
        server: ${{ secrets.FTP_SERVER }}  # This must match your GitHub Secrets
        username: ${{ secrets.FTP_USERNAME }}  # FTP Username stored in secrets
        password: ${{ secrets.FTP_PASSWORD }}  # FTP Password stored in secrets
        port: 21  # Default FTP port (adjust if needed)
        local-dir: ./  # Root directory of your Laravel project
        server-dir: ../  # Move one level up from public_html (root of your subdomain)
        exclude: |  # Exclude unnecessary files and folders
          .git*
          node_modules/
          vendor/
          public/  # Exclude public folder contents
          storage/logs/
        log-level: verbose
        timeout: 600
